### ISSUE TITLE
Clicking on Select Product... throws a 404 error

### ISSUE THREAD

**Issue by brandoniffert** [Jarlssen/Jarlssen_ChooserWidget#2]
Clicking on the Select Product... button throws a 404 error (over AJAX) I get the following error:

`Failed to load resource: the server responded with a status of 404 (Not Found) 
http://example.com/index.php/featuredproduct/catalog_product_widget/chooser/uniq_id/product97d2cd120a29ad1a1374dcdce28dea5d/key/d851ae3c0d4962bf9e4ac4ad9108dee4/?isAjax=true`

`featuredproduct` is the name of my custom module I am running the ChooserWidget in. I can provide any necessary files to help debug. I am running Magento CE 1.9.0.1

**Comment by ghost** [comment]
I have the same issue... what was the work around?
