### ISSUE TITLE
ReferenceError: WysiwygWidget is not defined

### ISSUE THREAD

**Issue by dmitryzar** [Jarlssen/Jarlssen_ChooserWidget#7]
Hello! I receive an error after installation: ReferenceError: WysiwygWidget is not defined
http://localhost19/index.php/background/adminhtml_background/edit/id/2/key/f2f45f2049956d18a81ca6730ded502a/

form.php
$model    = Mage::getModel('background/background');
$fieldset = $form->addFieldset('background_form', array(
            'legend'=>Mage::helper('background')->__('Background information')
        ));

$chooserHelper = Mage::helper('jarlssen_chooser_widget/chooser');
     $productChooserConfig = array(
    'input_name'  => 'product_name',
    'input_label' => $this->**('Custom entity'),
    'button_text' => $this->**('Select entity'),
    'required'    => true
    );
$chooserHelper->createProductChooser($model, $fieldset, $productChooserConfig);

WysiwygWidget to be connected?

**Comment by ceckoslab** [comment]
@myZmage Please add "editor" handle, refresh Magento cache and try again.

Here is described how to add "editor" handle: https://github.com/Jarlssen/Jarlssen_ChooserWidget

**Comment by dmitryzar** [comment]
Sorry, I did not notice. Everything worked. Thanks for the quick response.
